const InternalServer = require("../exceptions/internal-server")

exports.createBooking = async(req,res)=>{
    try {
        
    } catch (error) {
        InternalServer(res,error)
    }
}

exports.listBooking = async(req,res)=>{
    try {
        
    } catch (error) {
        InternalServer(res,error)
    }
}

exports.bookingById = async(req,res)=>{
    try {
        
    } catch (error) {
        InternalServer(res,error)
    }
}

exports.bookingUpdate = async(req,res)=>{
    try {
        
    } catch (error) {
        InternalServer(res,error)
    }
}

exports.bookingDelete = async(req,res)=>{
    try {
        
    } catch (error) {
        InternalServer(res,error)
    }
}
